dist: xenial
sudo: true
branches:
  only: 
    - master
    - dev
before_install:
  - sudo apt-get install -y libgconf-2-4
services:
  - xvfb
language: node_js
nodejs:
  - "lts/*"
cache:
  npm: true
  directories:
    - ~/.cache
notifications:
  email: false
