dist: xenial
sudo: true
branches:
  only: 
    - master
    - dev
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: node_js
nodejs:
  - "lts/*"
cache:
  yarn: true
  directories:
    - ~/.cache
notifications:
  email: false
