dist: xenial
sudo: true
branches:
  only: 
    - master
    - dev
before_install:
  - sudo apt-get update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: node_js
nodejs:
  - "lts/*"
cache:
  npm: true
  directories:
    - ~/.cache
notifications:
  email: false
