dist: xenial
sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
language: node_js
nodejs:
  - "lts/*"
cache:
  npm: true
  directories:
    - ~/.cache
notifications:
  email: false
